### ISSUE TITLE
Make a scatter plot grid of the development indicators 

### ISSUE THREAD

**Issue by tperrier** [tperrier/infx_598c#1]
Just like the one from the presentation but with:
- income
- internet
- economic
- mobiles
- population
- literacy
- urban 

7 variables might be to many: I would drop population and urban, but maybe some of the others would be less interesting

**Comment by fahadp** [comment]
Could not find income in the data but I have plotted against the other variables. Population is useless but others have some pattern.

![hiv_dev_factors](https://cloud.githubusercontent.com/assets/3515262/6632310/6b094bd6-c8f1-11e4-8e10-01485b88c81d.png)
![hiv_factors_wo_pop](https://cloud.githubusercontent.com/assets/3515262/6632308/6b0710dc-c8f1-11e4-9d9e-0742c78306a9.png)
![tb_dev_factors](https://cloud.githubusercontent.com/assets/3515262/6632309/6b091904-c8f1-11e4-9ca6-6e8f166810b1.png)
![tb_factors_wo_pop](https://cloud.githubusercontent.com/assets/3515262/6632311/6b09b3fa-c8f1-11e4-8cc9-750b2d36d4f6.png)

**Comment by tperrier** [comment]
Cool thanks, exactly what we need. Income was supposed to be economic (It's Gross National Income - GNI).

**Comment by tperrier** [comment]
Let's put this into a function inside analyze.py.  I think we can remove ground since it will be on the other one.  It doesn't look to bad.

**Comment by fahadp** [comment]
I have pushed some code. It has following function: get_scatter_grid_plot(df,features=['internet', 'economic', 'mobiles', 'literacy', 'urban'],colorkey='internet')

Example: get_scatter_grid_plot(hiv)

**Comment by tperrier** [comment]
Great, those both look good!
