### ISSUE TITLE
Plotting: plot_regress_exog  and use draw()

### ISSUE THREAD

**Issue by tperrier** [tperrier/infx_598c#2]
We need to make a function that makes plots like [this](http://statsmodels.sourceforge.net/devel/examples/notebooks/generated/example_regression_plots.html#Regression-Plots) using graphics.plot_regress_exog. 

We really only want the top two graphs, not the bottom two.  The top one comes from [plot_fit](http://statsmodels.sourceforge.net/0.5.0/generated/statsmodels.graphics.regressionplots.plot_fit.html#statsmodels.graphics.regressionplots.plot_fit) but I can't figure out the call for the second graph.  It looks like line [205 in regressionplots.py](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/graphics/regressionplots.py#L205) is what makes the call.

Also, plt.draw() is similar to plt.show() except that it doesn't block.  As long as you have code.interact() going then this is a much better option.

**Comment by fahadp** [comment]
I have pushed some code that include following functions:
def get_fitted_graph(df,features=['median','sd'],label='HIV')
def get_residue_graph(df,features=['median','sd'],label='HIV',exog_feature='median')

Example:
get_fitted_graph(hiv)
get_residue_graph(hiv,'median')
plt.show() #You need still need to call show() once after all the draw(). 

![fitted_graph](https://cloud.githubusercontent.com/assets/3515262/6633454/fe4bfd44-c905-11e4-87c3-4b68f19994c4.png)
![residue_graph](https://cloud.githubusercontent.com/assets/3515262/6633455/fe4e7d12-c905-11e4-9ac5-40eb19af1da9.png)
